### PR TITLE
Add support for Cargo projects in Drafter and in action macros

### PR DESCRIPTION
**Pull request by livingsilver94**
This is a rebase of #2 which was accidentally deleted by me.

### CODE REVIEW

**Comment by ermo** [comment]
@tarkah & @joebonrichie :

Does this look sane to you?

**Comment by ermo** [comment]
@livingsilver94 : Could you work with Joey on this? I don't know if he has work that supersedes yours.

**Comment by tarkah** [comment]
LGTM

**Review by tarkah — APPROVED** [review]

**Comment by ermo** [comment]
Superseded by #102 , so closing this.

**Pull request closed without merging**
